# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WilddogUIChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilddogUIChat
  pod 'WilddogUI', :path => '../'

  target 'WilddogUIChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
